[workspace]
members = [
  "route_router", 
  "route_derive", 
  "route_http", 
  "route_core"
]
resolver = "2"


[package]
name = "route"
edition = "2021"

[dependencies]
# route_router = {path = "./route_router", version = "0.1.0"}
route_derive = {path = "./route_derive", version = "0.1.0"}
route_http = {path = "./route_http", version = "0.1.0"}
route_core = {path = "./route_core", version = "0.1.0"}

tokio = { version = "1.38.0", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
# dyn-clone = "1.0.17"
matchit = "0.8.3"
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
futures-util = "0.3.30"
