[workspace]
resolver = "2"
members = [
  "titan",
  "titan-core",
  "titan-http", 
  "titan-utils",
  "titan-server",
  "titan-router",
  "titan-html",
  "titan-html-derive"
]

[workspace.package]
authors = ["Vincent Thomas"]
categories = ["Web programming"]
keywords = ["web"]
license = "MIT"
edition = "2021"
version = "0.1.0"
