[workspace]
resolver = "2"
members = [
  "route",
  "route_core",
  "route_http", 
  "route_utils",
  "route_server",
  "route_router",
  "route_html"
, "route_html_derive"]

[workspace.package]
authors = ["Vincent Thomas"]
categories = ["web"]
license = "MIT"
edition = "2021"
version = "0.1.0"
