[package]
name = "titan-router-derive"
authors.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
quote = "1.0.36"
syn = {version = "2.0.66"}
proc-macro2 = "1.0"

[lib]
proc-macro = true
