[package]
name = "route_http"
version.workspace = true
authors.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
futures-core = "0.3.31"
http = "1.1.0"
mime = "0.3.17"
