[package]
name = "route_http"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
bytes = "1"
http = "1.1.0"
serde_urlencoded = "0.7.1"
mime = "0.3.17"
