[package]
name = "route"
edition = "2021"

[dependencies]
route_http = {path = "../route_http", version = "0.1.0"}
route_core = {path = "../route_core", version = "0.1.0"}
route_server = {path = "../route_server", version = "0.1.0"}

matchit = "0.8.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_urlencoded = "0.7"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["rt","rt-multi-thread", "macros"] }
