[package]
name = "route_core"
version.workspace = true
authors.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
route_http = { path = "../route_http" }
tower = {version = "0.5.1", features = ["make", "buffer"]}
