[package]
name = "route_core"
version = "0.1.0"
edition = "2021"

[dependencies]
route_http = { version = "0.1.0", path = "../route_http" }
# tower-service = "0.3.2"

# pin-project-lite = "0.2.14"
# futures-core = "0.3.30"
# paste = "1"

async-trait = "0.1.81"