[package]
name = "route_server"
version.workspace = true
authors.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.38", features = ["rt","rt-multi-thread", "macros"] }
route = { version = "0.1.0", path = "../route" }
route_core = { path = "../route_core", version = "0.1.0" }
route_http = { workspace = true }
chrono = "0.4.38"