[package]
name = "route_server"
version.workspace = true
authors.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.42.0", features = ["net", "io-util", "rt"] }
tower-service = "0.3.3"
