[package]
name = "route_server"
version = "0.1.0"
edition = "2021"

[dependencies]
#smol = { version = "2" }
tokio = { version = "1.38", features = ["full"] }
route = { version = "0.1.0", path = "../route" }
#hyper = { version = "1", features = ["server", "http1"] }
#hyper-util = { version = "0.1", features = ["tokio"] }
#http-body-util = "0.1"
route_core = { path = "../route_core", version = "0.1.0" }
route_http = { path = "../route_http", version = "0.1.0", features = ["parser"] }