[package]
name = "route_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["rt","rt-multi-thread", "net"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
route_core = { path = "../route_core", version = "0.1.0" }
route_http = { path = "../route_http", version = "0.1.0" }