[package]
name = "route_derive"
version.workspace = true
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = {version = "2.0.66", features = ["full"]}
proc-macro2 = "1.0"

[lib]
proc-macro = true
