name: CI

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build
        run: cargo check
      - name: Run tests
        run: cargo test
