[package]
name = "route_router"
version = "0.1.0"
edition = "2021"

#[dev-dependencies]
#criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "router"
harness = false

[dependencies]
# dyn-clone = "1.0.17"
# route_http = {path = "../route_http", version = "0.1.0"}